# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/ernestio/ernest-config-client"

[[constraint]]
  branch = "master"
  name = "github.com/ernestio/ernestprovider"

[[constraint]]
  branch = "master"
  name = "github.com/nats-io/nats"

[[override]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v8.1.0-beta"
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v7.3.1"

[prune]
  go-tests = true
  unused-packages = true
